spring.application.name=weather-pincode
spring.datasource.url=jdbc:h2:mem:weatherdb
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

openweather.api.key=3b35802e8d41ba16c8896375609d1206
openweather.geocode.url=http://api.openweathermap.org/geo/1.0/zip
openweather.weather.url=https://api.openweathermap.org/data/2.5/weather

# Cache-specific
spring.cache.cache-names=pincodeCache,weatherCache
spring.cache.caffeine.spec=maximumSize=1000,expireAfterWrite=1h

# Override TTL for pincode cache (24 hours)
spring.cache.cache.pincodeCache.spec=maximumSize=1000,expireAfterWrite=24h
